### ISSUE TITLE
add a website for IRSeC

### ISSUE THREAD

**Issue by Bad3r** [ritsec/ritsec.github.io#28]
IRSeC doesn't have its own website like [ISTS](https://www.ists.io/)
the ISTS website can be cloned and modified for ISTS
also the [sponsor's page](https://www.ists.io/sponsors) on the ISTS website is outdated

**Comment by micahjmartin** [comment]
I dont think either of them really need their own website. We could host them on the same repo and they could each just have some custom pages. Or we could just have to repos since Gh pages is easy. 

It would be easiest just to link the sponsor page on the ISTS site back to the sponsor page on the main site. That would let us only have one place that we need to keep track of who is sponsoring
